// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

// The iOS side of the plugin, as a Swift package.
//
// Flutter 3.44 makes Swift Package Manager the default for iOS, and CocoaPods
// trunk becomes read only in December 2026. A plugin that ships only a podspec
// still builds today, because the tool falls back to CocoaPods for plugins that
// have not migrated, but it is a fallback with an end date.
//
// The podspec beside this stays, and both read the same sources. An app on
// CocoaPods and an app on Swift Package Manager get the same plugin, which is
// the point: this is additive, and nothing about the existing path changes.
//
// The minimum iOS version here matches `s.platform` in tolinku.podspec
// deliberately. Two manifests describing one plugin can disagree silently, so
// test/ios_package_test.dart asserts they do not.

import PackageDescription

let package = Package(
  name: "tolinku",
  platforms: [
    .iOS("12.0")
  ],
  products: [
    .library(name: "tolinku", targets: ["tolinku"])
  ],
  dependencies: [
    // Generated by the Flutter tool at build time, which is why nothing in the
    // repository sits at that path.
    .package(name: "FlutterFramework", path: "../FlutterFramework")
  ],
  targets: [
    .target(
      name: "tolinku",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework")
      ]
      // No resources and no privacy manifest. The plugin reads the current
      // timezone and the OS version string, neither of which is a required
      // reason API, and bundles nothing.
    )
  ]
)
