// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

// The iOS side of the plugin, as a Swift package.
//
// Flutter 3.44 makes Swift Package Manager the default for iOS, and CocoaPods
// trunk becomes read only in December 2026. A plugin that ships only a podspec
// still builds today, because the tool falls back to CocoaPods for plugins that
// have not migrated, but it is a fallback with an end date.
//
// The podspec beside this stays, and both read the same sources. An app on
// CocoaPods and an app on Swift Package Manager get the same plugin, which is
// the point: this is additive, and nothing about the existing path changes.
//
// The minimum iOS version here matches `s.platform` in tolinku.podspec
// deliberately. Two manifests describing one plugin can disagree silently, so
// test/ios_package_test.dart asserts they do not.
//
// 13.0 is Flutter's own floor, not a choice: `deploymentTarget()` in
// flutter_tools returns 13.0 for iOS, so a plugin claiming 12.0 was promising a
// version Flutter will not run on. It also had a concrete cost, because the
// generated FlutterFramework package declares 13.0 and Swift Package Manager
// refuses a dependency whose deployment target is above the depending target's.

import PackageDescription

let package = Package(
  name: "tolinku",
  platforms: [
    .iOS("13.0")
  ],
  products: [
    .library(name: "tolinku", targets: ["tolinku"])
  ],
  dependencies: [
    // Generated by the Flutter tool at build time, which is why nothing in the
    // repository sits at that path. The tool only began generating it in
    // Flutter 3.41, which is why pubspec.yaml asks for that version: a package
    // manifest pointing at a directory the tool never writes does not degrade,
    // it fails resolution outright.
    .package(name: "FlutterFramework", path: "../FlutterFramework")
  ],
  targets: [
    .target(
      name: "tolinku",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework")
      ],
      resources: [
        // Not required by Apple for what this plugin calls. It is here because
        // the app embedding an attribution SDK has to describe our data flows
        // in its own privacy label. See the file for what it declares.
        .process("PrivacyInfo.xcprivacy")
      ]
    )
  ]
)
